FoodHallApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodHallApp.Data;
using FoodHallApp.Models;
using FoodHallApp.Models.ViewModels;
using Microsoft.AspNetCore.Http;

namespace FoodHallApp.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly FoodHallAppContext _context;

        public CategoriesController(FoodHallAppContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var model = new CategoryViewModel
            {
                Categories = await _context.Category.ToListAsync()
            };
            return View(model);
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryViewModel model)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            if (ModelState.IsValid)
            {
                var category = new Category
                {
                    CategoryName = model.CategoryName,
                };
                _context.Category.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int cID, CategoryViewModel model)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var category = await _context.Category.FirstOrDefaultAsync(c => c.CategoryID == cID);
            if (category == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                category.CategoryName = model.CategoryName;
                _context.Category.Update(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int cID)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var category = await _context.Category.FirstOrDefaultAsync(c => c.CategoryID == cID);
            if(category == null)
            {
                return NotFound();
            }
            else
            {
                _context.Category.Remove(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryID == id);
        }
    }
}

FoodHallApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodHallApp.Data;
using FoodHallApp.Models;
using FoodHallApp.Models.ViewModels;
using Microsoft.AspNetCore.Http;

namespace FoodHallApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly FoodHallAppContext _context;

        public OrdersController(FoodHallAppContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var model = new OrderViewModel
            {
                Orders = await _context.Order.Include(o => o.OrderedProducts).ThenInclude(o => o.Product).Include(o => o.Customer).ToListAsync()
            };
            return View(model);
        }

        public async Task<IActionResult> Processed(int id)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var order = await _context.Order.Include(o => o.OrderedProducts).FirstOrDefaultAsync(o => o.OrderID == id);
            foreach (var prod in order.OrderedProducts)
            {
                _context.OrderedProducts.Remove(prod);
            }
            _context.Order.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.OrderID == id);
        }
    }
}

FoodHallApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodHallApp.Data;
using FoodHallApp.Models;
using FoodHallApp.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace FoodHallApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly FoodHallAppContext _context;
        private readonly IWebHostEnvironment _environment;

        public ProductsController(FoodHallAppContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Products
        public async Task<IActionResult> Index(int? ProductCategory)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var model = new ProductViewModel();
            ViewData["category"] = new SelectList(_context.Category, "CategoryID", "CategoryName", ProductCategory);

            model.Products =await _context.Product.ToListAsync();
            if (ProductCategory != null)
            {
                model.Products = await _context.Product.Where(p => p.CategoryID == ProductCategory).ToListAsync();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel model)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            if (ModelState.IsValid)
            {
                string filename = UploadedFile(model.Photo);
                var product = new Product
                {
                    ProductName = model.ProductName,
                    Price = model.Price,
                    CategoryID = model.ProductCategory,
                    Photo = filename
                    
                };
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        private string UploadedFile(IFormFile photo)
        {
            string file = "Pabo";
            if (photo != null)
            {
                string folderPath = Path.Combine(_environment.WebRootPath, "img");
                file = Guid.NewGuid().ToString() + "_" + photo.FileName;
                string filePath = Path.Combine(folderPath, file);
                using(var filestream = new FileStream(filePath, FileMode.Create))
                {
                    photo.CopyTo(filestream);
                }
            }
            return file;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int pID, ProductViewModel model)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var product = await _context.Product.FindAsync(pID);
            if (product == null)
            {
                return NotFound();
            }

            DeleteFile(product.Photo);

            if (ModelState.IsValid)
            {
                string filePath = UploadedFile(model.Photo);
                product.ProductName = model.ProductName;
                product.Price = model.Price;
                product.CategoryID = model.ProductCategory;
                product.Photo = filePath;
                _context.Product.Update(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // POST: Products/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int pID)
        {
            if (HttpContext.Session.GetString("adminname") == null)
            {
                return RedirectToAction("Login", "Home", new { msg = "Login first!" });
            }
            var product = await _context.Product.FindAsync(pID);
            if(product == null)
            {
                return NotFound();
            }
            else
            {
                DeleteFile(product.Photo);
                _context.Product.Remove(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        private void DeleteFile(string photo)
        {
            string path = Path.Combine(_environment.WebRootPath, "img");
            string filepath = Path.Combine(path, photo);
            System.IO.File.Delete(filepath);
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductID == id);
        }
    }
}

FoodHallApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food Hall</title>
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crete+Round" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav style="min-height: 60px" class="navbar navbar-expand-md navbar-dark bg-danger pl-5 pr-5">
            <a class="navbar-brand ml-5" href="#">Food Hall</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Signup">Signup</a>
                    </li>

                </ul>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <div class="footer bg-dark">
        <div class="row">
            <div class="col">
                <div class="container">
                    <p class="text-white pt-3 text-center">Foodhall &copy; A product by Ashikur Rahman</p>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

FoodHallApp/Views/Shared/_Layout2.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor acccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food Hall</title>
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crete+Round" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav style="min-height: 60px" class="navbar navbar-expand-md navbar-dark bg-danger pl-5 pr-5">
            <a class="navbar-brand ml-5" href="#">Food Hall</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Orders" asp-action="Index">Order</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Products" asp-action="Index">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Categories" asp-action="Index">Categories</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @acccessor.HttpContext.Session.GetString("adminname")
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Home" asp-action="Logout">Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <div class="footer bg-dark">
        <div class="row">
            <div class="col">
                <div class="container">
                    <p class="text-white pt-3 text-center">Foodhall &copy; A product by Ashikur Rahman</p>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>